fieldLayouts:
  4685f10e-9929-4fd8-8fbf-e5138c7a622f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eefd5ea4-a950-49fe-b781-0fa199e92089
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76dc1793-73fa-4e5e-8acc-0f275a21f4c8
        userCondition: null
handle: slider
hasTitleField: true
name: Slider
section: 31037613-c6a8-4370-8c9c-835060e195ac # Slider
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
