defaultPlacement: end
enableVersioning: true
handle: slider
name: Slider
propagationMethod: all
siteSettings:
  f560a16e-a528-41e1-b75b-c41d266859d5: # Test Ddev
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
